---

- name: check if keystore exists
  stat:
    path: "{{ data.dest }}"
  register: _java_keystore_exists
  changed_when: no

- name: create password file
  tempfile:
    state: file
  register: _java_keystore_tempfile
  check_mode: no
  changed_when: no

- debug: var=_java_keystore_exists
- debug: var=_java_keystore_tempfile
- debug: var=data.password

- name: create the temporary password file
  copy:
    content: "{{ data.password }}"
    dest: "{{ _java_keystore_tempfile.path }}"
  when: _java_keystore_exists.stat.exists == false

- name: create keystore
  command: '{{ java.home }}/bin/keytool -genkeypair -alias {{ data.alias }} -keyalg {{ data.keyalg|default("rsa") }} -keysize {{ data.keysize|default(2048) }} -ext SAN={{ data.san }} -ext KU=digitalSignature,keyEncipherment,dataEncipherment -ext EKU=serverAuth,clientAuth -ext BC:critical=ca:false -dname "{{ data.dn }}" -validity {{ data.validity|default(825) }} -keystore {{ data.dest }} -keypass:file {{ _java_keystore_tempfile.path }} -storepass:file {{ _java_keystore_tempfile.path }}'
  args:
    creates: "{{ data.dest }}"

- name: remove tempfile
  file:
    path: "{{ _java_keystore_tempfile.path }}"
    state: absent
  changed_when: no
  check_mode: no
