---

- name: import certificate into truststore
  java_cert:
    executable: "{{ java.home }}/bin/keytool"
    cert_alias: "{{ data.alias }}"
    cert_path: "{{ data.src }}"
    keystore_path: "{{ data.keystore }}"
    keystore_pass: "{{ data.password }}"
    keystore_create: yes
    state: present
